### ISSUE TITLE
can't get __overwrite to work

### ISSUE THREAD

**Issue by disaster123** [bbinet/pillarstack#23]
sls from normal pillar:
ssh:
  other:
  users:
    root:
      keys:
        - efg
        - abc

yaml included in stack.cfg:
ssh:
  users:
    root:
      keys:
        - __: overwrite
        - lala

resulting pillar.items is now:
ssh:
  other:
  users:
    root:
      keys:
        - efg
        - abc
        - lala

**Comment by bbinet** [comment]
This is expected. See ext_pillar documentation in saltstack: https://docs.saltstack.com/en/latest/topics/development/external_pillars.html#ext-pillar => "This function should return a dictionary, the contents of which are merged in with all of the other pillars and returned to the minion."

PillarStack cannot prevent salt to merge the stack result with previous pillar.
So instead you can move your initial pillar data to PillarStack too and it should work the way you want.
