### ISSUE TITLE
feature request git_stack using the same method as git_pillar...

### ISSUE THREAD

**Issue by aboe76** [bbinet/pillarstack#24]
I would like to have the same options as git_pillar to use something like:

```
gitfs_provider: 'pygit2'
git_stack_pubkey: /etc/salt/stack_rsa.pubkey
git_stack_privkey: /etc/salt/stack_rsa
ext_pillar:
  - stack:
    - master git@github.com:test/stack.git
```

Where stack will use the same setup as git_pillar.

**Comment by aboe76** [comment]
Or if this is too much, maybe just have the stack.cfg not hardcoded as a path:
but also via fileserver_backend:
```
ext_pillar:
  stack: salt://salt/stack/stack.cfg
```
That way the default gitfs_remotes can be used.

**Comment by bbinet** [comment]
pull request welcome ;-)

**Comment by bbinet** [comment]
For those interested in a Git backend for PillarStack, thanks to @amendlik, this is now possible using its repository:
https://github.com/amendlik/gitstack-pillar

So this issue can now be closed.
