### ISSUE TITLE
Loop in pillarstack

### ISSUE THREAD

**Issue by n-rodriguez** [bbinet/pillarstack#25]
Hi!

I've got this in one of my pillar :

```
{% set interfaces = [] %}

{% for iface, addresses in __grains__['ip_interfaces'].items() %}
  {% if addresses != [] and iface != 'lo' %}
    {% do interfaces.append(iface) %}
  {% endif %}
{% endfor %}
```

But it doesn't work. Salt/Pillarstack throws an error :
`[CRITICAL] Pillar render error: Failed to load ext_pillar stack: Encountered unknown tag 'do'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.`

It seems that Jinja2 `Environment` doesn't have the `do` extension loaded.

To solve this you can either declare `Environment` like this :
`jenv = Environment(loader=FileSystemLoader(basedir), extensions=['jinja2.ext.do'])`
or 
`jenv.add_extension('jinja2.ext.do')`

**Comment by bbinet** [comment]
Ok, feel free to submit a pull request with this change.
Thanks :)

**Comment by n-rodriguez** [comment]
Done : https://github.com/bbinet/pillarstack/pull/26

**Comment by n-rodriguez** [comment]
Thank you!
