### ISSUE TITLE
Pillar stack doesn't work with sub-directories when using Windows standalone minion 

### ISSUE THREAD

**Issue by sbreidba** [bbinet/pillarstack#28]
When using a standalone Windows minion via `salt-call`, the `glob` function used to enumerate the YAML files creates the list of files using OS-specific separators. Unfortunately, the YAML `FileSystemLoader` class expects paths to always use UNIX-style directory separators, causing the load to fail.

I have a fix for this if you're interested.

**Comment by bbinet** [comment]
If it still works with linux minions, I'd be happy to merge your fix, thanks.

**Comment by sbreidba** [comment]
For sure. I'll include a simple test script that I used to test the fix independently as well as validating that things still work on linux.
