### ISSUE TITLE
Sync with Salt repo

### ISSUE THREAD

**Issue by n-rodriguez** [bbinet/pillarstack#31]
Hi! Do you know when the new version of ```stack.py``` will be available / merged in Salt repo?

**Comment by bbinet** [comment]
I've just submitted a pull request to saltstack repository to sync with the latest pillarstack upstream changes:
https://github.com/saltstack/salt/pull/40541

**Comment by n-rodriguez** [comment]
Thanks!

**Comment by bbinet** [comment]
In the mean time you can manually install the latest pillarstack file by following the installation section in the readme:
https://github.com/bbinet/pillarstack#installation

**Comment by n-rodriguez** [comment]
yes, that's what I did ;) thank you!
