### ISSUE TITLE
unable to use asterisk(*) with pillar stack

### ISSUE THREAD

**Issue by pratik705** [bbinet/pillarstack#36]
- I have configured pillar stack[1]. As per example provided in [1], we can use asterisk(*) in stack.cfg. But, for me its not working. It fails with an error.
`Ignoring pillar stack template "minions/salt-master.novalocal/*.yml": can't find from root dir "/srv/salt/external.pillar"`

[1] https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.stack.html

# Steps to Reproduce Issue

- configure pillarstack as per above link[1].

cat /srv/salt/external.pillar/stack.cfg
common.yml
minions/{{ minion_id }}/*.yml <==

ls /srv/salt/external.pillar/minions/salt-master.novalocal/
12345.yml <==

- Though "12345.yml" is present, if I try to fetch the pillar data, I dont see data populated from "12345.yml" file.

salt 'salt-master.novalocal' pillar.items <==

- From debug logs:
`
2017-10-27 20:24:55,215 [salt.loaded.ext.pillar.stack][DEBUG ][18736] Config: /srv/salt/external.pillar/stack.cfg 2017-10-27 20:24:55,217 [salt.loaded.ext.pillar.stack][DEBUG ][18736] YAML: basedir=/srv/salt/external.pillar, path=common.yml 2017-10-27 20:24:55,236 [salt.loaded.ext.pillar.stack][DEBUG ][18736] YAML: basedir=/srv/salt/external.pillar, path=minions/salt-master.novalocal/*.yml 2017-10-27 20:24:55,236 [salt.loaded.ext.pillar.stack][INFO ][18736] Ignoring pillar stack template "minions/salt-master.novalocal/*.yml": can't find from root dir "/srv/salt/external.pillar"
`

- But, it works if I specify "file name"(12345.yml) in stack.cfg file.

- Can anyone please help me to understand the cause? Is it documentation bug?

- How I can include all "*.yml" files from "minions/{{ minion_id }}/" directory?

# Versions Report

salt --versions-report
Salt Version:
Salt: 2017.7.2

Dependency Versions:
cffi: 1.11.1
cherrypy: unknown
dateutil: 2.6.1
docker-py: Not Installed
gitdb: Not Installed
gitpython: Not Installed
ioflo: Not Installed
Jinja2: 2.9.6
libgit2: Not Installed
libnacl: Not Installed
M2Crypto: Not Installed
Mako: 1.0.7
msgpack-pure: Not Installed
msgpack-python: 0.4.8
mysql-python: Not Installed
pycparser: 2.18
pycrypto: 2.6.1
pycryptodome: Not Installed
pygit2: Not Installed
Python: 2.7.5 (default, Aug 4 2017, 00:39:18)
python-gnupg: Not Installed
PyYAML: 3.12
PyZMQ: 15.3.0
RAET: Not Installed
smmap: Not Installed
timelib: Not Installed
Tornado: 4.2.1
ZMQ: 4.1.4

System Versions:
dist: centos 7.4.1708 Core
locale: UTF-8
machine: x86_64
release: 3.10.0-693.el7.x86_64
system: Linux
version: CentOS Linux 7.4.1708 Core

**Comment by bbinet** [comment]
Can you show the output of the following command?
```
ls -l /srv/salt/external.pillar/minions/salt-master.novalocal/*.yml
```

**Comment by pratik705** [comment]
@bbinet :

ls -l /srv/salt/external.pillar/minions/salt-master.novalocal/*.yml
`
-rw-r--r--. 1 root root 193 Oct 27 20:49 /srv/salt/external.pillar/minions/salt-master.novalocal/12345.yml
`

**Comment by bbinet** [comment]
Hum, this might be a bug, but this is weird as it is basic functionality and it works for me.

Can you run a python shell with the following commands:
```
$ python
>>> import os
>>> from glob import glob
>>> basedir = "/srv/salt/external.pillar"
>>> item = "minions/salt-master.novalocal/*.yml"
>>> print(glob(os.path.join(basedir, item)))
```

**Comment by bbinet** [comment]
(and show me the output)

**Comment by pratik705** [comment]
>>> import os
>>> from glob import glob
>>> basedir = "/srv/salt/external.pillar"
>>> item = "minions/salt-master.novalocal/*.yml"
>>> print(glob(os.path.join(basedir, item)))
['/srv/salt/external.pillar/minions/salt-master.novalocal/12345.yml']


@bbinet is it working for you with the same salt version? Do you suspect any configuration issue?

**Comment by bbinet** [comment]
no you configuration seems ok, I've just tried to reproduce what is doing pillarstack here:
https://github.com/bbinet/pillarstack/blob/master/stack.py#L77
when you get the log message:
`[salt.loaded.ext.pillar.stack][INFO ][18736] Ignoring pillar stack template "minions/salt-master.novalocal/*.yml": can't find from root dir "/srv/salt/external.pillar"`

But when you do it manually with python it works, that is strange.

**Comment by pratik705** [comment]
@bbinet my bad. i just noticed from file_root, there was another stack.py copied in modules. I removed it and now its working fine.

**Comment by bbinet** [comment]
Good news this is working now :)
