### ISSUE TITLE
Lower "Ignoring pillar stack template" log level

### ISSUE THREAD

**Issue by mchugh19** [bbinet/pillarstack#41]
Pillarstack includes a warning level log item when a configured directory cannot be found. 

We are using pillarstack so that we can include files when they exist, but a missing file is not necessarily indicative of a problem. 

Where our pillarstack.cfg includes something like the following:
```
{%- for role in __grains__.get('ec2_roles', []) %}
roles/{{ role }}.yml
roles/{{ __grains__['ec2_tags']['Environment'] }}_{{ role }}.yml
roles/{{ __grains__['ec2_tags']['ApplicationName'] }}_{{ role }}.yml
{%- endfor %}
```

We see the following in the salt-master's log. 
```
[WARNING ] Ignoring pillar stack template "roles/cloud-services-shared_SaltMaster.yml": can't find from root dir "/var/cache/salt/master/git_pillar/1..."
[WARNING ] Ignoring pillar stack template "roles/.yml": can't find from root dir "/var/cache/salt/master/git_pillar/..."
```

Perhaps it would make sense to lower this log level down to info as it doesn't need to be reported in the normal use case? 

Thanks!

**Comment by bbinet** [comment]
@mchugh19 Yes I think it makes sense to lower to log level down to info. Can you submit a PR for that?
