### ISSUE TITLE
Issue with AWS metadata/salt http query and local variable injection

### ISSUE THREAD

**Issue by xandrellas** [bbinet/pillarstack#46]
In using pillarstack, attempting to have a host get its AWS subnet-id presented as pillar data is showing the following behavior.  Please advise. 

/srv/pillar/stack/roles/haproxy.sls:
`{% set mac_pillar = __grains__['hwaddr_interfaces']['eth0'] %}`
`{% set subnet_id = __salt__['http.query']('http://169.254.169.254/latest/meta-data/network/interfaces/macs/%s/subnet-id'|format(mac_pillar))['body'] %}`

`subnet_id: {{ subnet_id }}`
`test_val: string-of-random-stuff`

root@redacted-master:/srv/pillar/stack# `salt '*hap*' pillar.item subnet_id`
redacted-target-haproxy-host:
    ----------
    subnet_id:
        None

root@redacted-master:/srv/pillar/stack# `salt '*hap*' pillar.item test_val`
redacted-target-haproxy-host:
    ----------
    test_val:
        string-of-random-stuff

**Comment by ze42** [comment]
The http.query is done on the `master`, not on the host you hope to get a pillar for.

If you want information for the minion you should either:
  * Have custom `grains` on the minion so it can present information to the master. (see https://github.com/saltstack/salt-contrib/blob/master/grains/ec2_info.py )
  * Have a custom pillar that manages to get informations form aws API... but might require more information about the minion, and rights to describe instances on AWS, ... and would still require to get basic info (instance-id, and possibly account, ...)

**Comment by xandrellas** [comment]
Hey ze42 - not to be contrary but is that certain about that in regards to http.query?

we leverage data in pillar stack heavily that is reliant upon bits such as grains calls to os, fqdn, hostname, id, curl'ing AWS metadata for availability zone.  is http query an outlier in its approach?

we're currently presenting AWS metadata as a grain via salt minion configuration but the issue still stands in how to sniff out and move past a non-static value i.e. the MAC address of the minion in question.

I originally had worked with gtmanfred on this of which he presented the initial code I OP'd with and he proved it from a non-pillarstack approach (top.sls and a pillar.sls file).  Which leads to my confusion as to the differentiation with pillar stack.

Thoughts?

**Comment by ze42** [comment]
Hello,

Not sure I understand everything, but here are some clarifications:

All the pillar generation, including salt[function] cals, are executed on the master itself.

The context makes it that pillars and grains are the one regarding the minion, but the code is still executed on the master. (grains.xxx, pillar.xxx would be executed on the master, but with the minion context...)

If you have non-static data in your grains, you should probably try to call some function that would refresh them, then the pillars to have the latest values at times. But that's not something pillar-stack can help with.



mmm... when you state `presenting AWS metadata as a grain via salt minion configuration`, do you mean you place stuffs directly in `/etc/salt/grains` ? If so, don't. Get more stuffs from dynamic grains, like the one linked earlier. You already get the mac from dynamic grains, and that part works properly enough. Having the previous grains in `salt://_grains/` would let it retrieve and place `ec2` grains with alot of useful info.

**Comment by xandrellas** [comment]
Hi Ze I'm referring to enabling AWS metadata as a grain via https://docs.saltstack.com/en/2017.7/ref/grains/all/salt.grains.metadata.html 

We don't present custom grains i.e. /etc/salt/grains yeah not my kind of use case.  

I'll look into the ec2 info

**Comment by xandrellas** [comment]
But the issue still stands in that : using non-pillarstack approach, my original post parses correctly and can get the subnet-id of the hosts presented such pillar data.  When attempting to translate it to pillarstack usage, I get the subnet_id: none returner.

**Comment by ze42** [comment]
`ec2_info` basictly would give the same as your exposed metadata, but in a dedicated namespace.

What do you get exactly when you use that code in _regular_ pillars?

As pillar (and pillarstack) are executed on the master, the query should both be placed there, and shouldn't work, as the master doesn't have any meta-data for the minion mac address.

But if you already expose your metadata via grains, you should then be able access them that way:

```
{% set mac_pillar = __grains__['hwaddr_interfaces']['eth0'] %}
{% set subnet_id = __grains__['meta-data']['network']['interfaces']['macs'][mac_pillar]['subnet-id'] %}
```

**Comment by xandrellas** [comment]
Hey Ze I apologize for the confusion on this.  Your statements have been convincing and have also assisted.  I will close out this incorrect issue and thank you
